# Generated by Django 3.2 on 2021-05-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
